### ISSUE TITLE
Cannot Start Application

### ISSUE THREAD

**Issue by nuke** [play/play-windows#6]
"Cannot continue. The application is improperly formatted. Contact the application vendor for assistance."

This dialogue appears after running setup.exe. I'm running Windows 7 64 bit.

Thanks!

**Comment by tjackowiak** [comment]
Same for me. Win 7 64bit.
Full error details: https://gist.github.com/2844085

**Comment by nuclearsandwich** [comment]
I also have this issue. :(:( Forked tjackowiak's gist and put my own error message. https://gist.github.com/2963591

**Comment by anaisbetts** [comment]
Sorry guys, this is because of my F'd Visual Studio install. Building the app from source will work

**Comment by hxrealm** [comment]
same for me Win7 64bit.

I don't know, how to solution, can you help me ?

**Comment by vikasbangade** [comment]
same for me can any one tell me solution

**Comment by nuclearsandwich** [comment]
@vikasbangade there's no eminent solution and the issue is two years outstanding. If you can build it from source like @paulcbetts said than this will work.

**Comment by anaisbetts** [comment]
This app isn't really even compatible with the current version of Play. Recommend this app be ignored :)
